services:
  postgres:
    image: postgres:16
    container_name: jobrunner-postgres
    environment:
      POSTGRES_DB: jobs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: jobrunner-redis
    ports:
      - "6379:6379"